export const FORMS_BUSINESS_DETAILS_UPDATE_FIELD = "FORMS_BUSINESS_DETAILS_UPDATE_FIELD";
export const FORMS_BUSINESS_DETAILS_SET_FIELDS = "FORMS_BUSINESS_DETAILS_SET_FIELDS";
export const FORMS_BUSINESS_DETAILS_RESET = "FORMS_BUSINESS_DETAILS_RESET";


export const FORMS_LEGAL_REPRESENTATIVE_UPDATE_FIELD = "FORMS_LEGAL_REPRESENTATIVE_UPDATE_FIELD";
export const FORMS_LEGAL_REPRESENTATIVE_SET_FIELDS = "FORMS_LEGAL_REPRESENTATIVE_SET_FIELDS";
export const FORMS_LEGAL_REPRESENTATIVE_RESET = "FORMS_LEGAL_REPRESENTATIVE_RESET";

export const FORMS_PERSON_UPDATE_FIELD = "FORMS_PERSON_UPDATE_FIELD";
export const FORMS_PERSON_SET_FIELDS = "FORMS_PERSON_SET_FIELDS";
export const FORMS_PERSON_RESET = "FORMS_PERSON_RESET";

// export const FORMS_LEGAL_REPRESENTATIVE_SET_FIELDS = "FORMS_LEGAL_REPRESENTATIVE_SET_FIELDS";
// export const FORMS_LEGAL_REPRESENTATIVE_SET_FIELDS = "FORMS_LEGAL_REPRESENTATIVE_SET_FIELDS";

export const FORMS_RESET = "FORMS_RESET";