export const SET_LOADING = "SET_LOADING";
export const UNSET_LOADING = "UNSET_LOADING";
export const SET_USER = "SET_USER";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_HQ = "SET_HQ";
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";
export const SET_HOUSEHOLD_CONTEXT = "SET_HOUSEHOLD_CONTEXT";
export const SET_ORGANIZATION_CONTEXT = "SET_ORGANIZATION_CONTEXT";
export const SET_PROGRAM_CONTEXT = "SET_PROGRAM_CONTEXT";

export const RESET_APP = "RESET_APP";

export const NEW_ORGANIZATION_SET_BUSINESS_DETAILS = "NEW_ORGANIZATION_SET_BUSINESS_DETAILS ";
export const NEW_ORGANIZATION_SET_LEGAL_REPRESENTATIVE = "NEW_ORGANIZATION_SET_LEGAL_REPRESENTATIVE";


/**
 * ACTIONS
 * SET_USER
 * CLEAR_USER
 * SET_CONTEXTS
 * SET_HOUSEHOLD_CONTEXT
 * SET_ORGANIZATION_CONTEXT
 * SET_PROGRAM_CONTEXT
 * SET_LOADING
 * UNSET_LOADING
 * SET_AUTHENTICATED
 * UNSET_AUTHENTICATED
 * 
 */
