export const ORGANIZATION_SETUP_SET_BUSINESS_DETAILS      = "ORGANIZATION_SETUP_SET_BUSINESS_DETAILS";
export const ORGANIZATION_SETUP_SET_LEGAL_REPRESENTATIVE  = "ORGANIZATION_SETUP_SET_LEGAL_REPRESENTATIVE";
export const ORGANIZATION_SETUP_SET_PAYMENT_METHODS       = "ORGANIZATION_SETUP_SET_PAYMENT_METHODS";
export const ORGANIZATION_SETUP_RESET                     = "ORGANIZATION_SETUP_RESET";
