export const HQ_HOUSEHOLDS_SET_CURRENT_DATA = "HQ_SET_CURRENT_DATA";
export const HQ_HOUSEHOLDS_SET_HOUSEHOLD_SELECTION = "HQ_SET_HOUSEHOLD_SELECTION";
export const HQ_SET_DASHBOARD_STATS = "HQ_SET_DASHBOARD_STATS";
