export const SET_HOUSEHOLD_MEMBERS = "SET_HOUSEHOLD_MEMBERS";
export const SET_PROGRAM_DETAILS = "SET_PROGRAM_DETAILS";
export const UNSET_PROGRAM_DETAILS = "UNSET_PROGRAM_DETAILS";
export const SET_PROGRAM_SEARCH_RESULTS = "SET_PROGRAM_SEARCH_RESULTS";
export const UNSET_PROGRAM_SEARCH_RESULTS = "UNSET_PROGRAM_SEARCH_RESULTS";
export const SET_PAYMENT_METHODS = "SET_PAYMENT_METHODS";

export const REGISTER_PLAYER_INIT = "REGISTER_PLAYER_INIT";
export const REGISTER_PLAYER_CLEAR = "REGISTER_PLAYER_CLEAR";
export const REGISTER_PLAYER_SET_PLAYERS = "REGISTER_PLAYER_SET_PLAYERS";
export const REGISTER_PLAYER_SET_CART = "REGISTER_PLAYER_SET_CART";
export const REGISTER_PLAYER_SET_DIVISIONS = "REGISTER_PLAYER_SET_DIVISIONS";
export const REGISTER_PLAYER_SET_QUESTIONS = "REGISTER_PLAYER_SET_QUESTIONS";
export const REGISTER_PLAYER_SET_PAYMENT_PLANS = "REGISTER_PLAYER_SET_PAYMENT_PLANS";
export const REGISTER_PLAYER_SET_QUESTIONS_ANSWERS = "REGISTER_PLAYER_SET_QUESTIONS_ANSWERS";

export const REGISTER_PLAYER_SET_DIVISION = "REGISTER_PLAYER_SET_DIVISION";
export const REGISTER_PLAYER_SET_PLAYER = "REGISTER_PLAYER_SET_PLAYER";

export const REGISTER_PLAYER_SET_PROFILE_ID = "REGISTER_PLAYER_SET_PROFILE_ID";
export const REGISTER_PLAYER_SET_PAYMENT_PLAN_ID = "REGISTER_PLAYER_SET_PAYMENT_PLAN_ID";
export const REGISTER_PLAYER_SET_PAYMENT_METHOD_ID = "REGISTER_PLAYER_SET_PAYMENT_METHOD_ID";
export const REGISTER_PLAYER_SET_CART_ID = "REGISTER_PLAYER_SET_CART_ID";
export const REGISTER_PLAYER_SET_REGISTRATION_ID = "REGISTER_PLAYER_SET_REGISTRATION_ID";